### ISSUE TITLE
[ENH] support changing org-attach-id-dir

### ISSUE THREAD

**Issue by tshu-w** [org-roam/org-roam-ui#153]
I found org-roam-ui node preview cannot find the right location of attachment images, which makes the picture impossible to show

my attach image dir is in `/Users/username/Documents/Org/attach/F9/A32912-7A61-48EE-9239-D3ECC683F411/2021-01-27_15-04-06_Screen Shot 2021-01-27 at 3.03.05 PM.png` but org-roam-ui tried to find it at `/Users/username/Documents/Org/notes/refs/data/F9/A32912-7A61-48EE-9239-D3ECC683F411/2021-01-27_15-04-06_Screen Shot 2021-01-27 at 3.03.05 PM.png`

my org-attach config:
```emacs-lisp
  (use-package org-attach
    :defer t
    :commands (org-attach-follow org-attach-complete-link)
    :init
    (org-link-set-parameters "attachment"
                             :follow #'org-attach-follow
                             :complete #'org-attach-complete-link)
    :config
    (setq org-attach-archive-delete 'query
          org-attach-id-dir (concat org-directory "attach/")
          org-attach-method 'mv
          org-attach-store-link-p 'file))

```

<img width="408" alt="Screen Shot 2021-11-16 at 15 09 13" src="https://user-images.githubusercontent.com/13161779/141938209-a2efb67e-e85f-4071-9bd0-acbdcd9e88cc.png">

**Comment by tshu-w** [comment]
In addition, I tried to add a soft link to the correct attach folder in the note directory, I find the image is not scaled
<img width="385" alt="Screen Shot 2021-11-16 at 15 25 12" src="https://user-images.githubusercontent.com/13161779/141939870-b5da8ef7-7764-4d00-9645-183ddc98c8f3.png">

**Comment by ThomasFKJorna** [comment]
Are you using `$HOME` here as a shorthand for the sake of the issue or is that the literal path that org-roam-ui tries to find? 
Is the added `"` the issue?

Could you check the "Network" tab in the developer tools (F12) and send me a screenshot?

Lots of questions, I know, but that will help!

And the scaling issue is known, it's just because I haven't figured out how to use Next.js image component, I'll get on it!

**Comment by tshu-w** [comment]
@ThomasFKJorna Thx you for the quick reply. 
> Are you using `$HOME` here as a shorthand for the sake of the issue or is that the literal path that org-roam-ui tries to find?

I'm using `$HOME` as a replacement for `/Users/username` and I have corrected it to avoid confusion. 

> Is the added `"` the issue?

I missed typing it and have removed it.

> Could you check the "Network" tab in the developer tools (F12) and send me a screenshot?

<img width="1893" alt="Screen Shot 2021-11-16 at 20 07 47" src="https://user-images.githubusercontent.com/13161779/141982701-ff3540d3-95c5-47f6-b0ae-9b01cf1f4c7e.png">
I tried to open image in new tab and got
<img width="2008" alt="Screen Shot 2021-11-16 at 20 07 54" src="https://user-images.githubusercontent.com/13161779/141982755-15d37dae-61b1-4b3f-bfc1-43a3e76e2949.png">
so I thought org-roam-ui request the wrong path.

**Comment by rasendubi** [comment]
Another thing to note: changing org-attach-id-dir to non-standard location requires changing idDir option in uniorg-attach (https://github.com/rasendubi/uniorg/tree/master/packages/uniorg-attach#options) which org-roam-ui doesn't do. This is likely the root cause.

**Comment by ThomasFKJorna** [comment]
I'll have a look in a bit. For now, the image scaling issue should be fixed!

**Comment by ThomasFKJorna** [comment]
Ah nevermind, I clearly hadn't finished my coffee yet, I could not tell that the two paths differed! I will update the uniorg attach setting!

**Comment by ThomasFKJorna** [comment]
Thanks @rasendubi, this would have taken me quite a while to figure out on my own 😅

**Comment by tshu-w** [comment]
> I'll have a look in a bit. For now, the image scaling issue should be fixed!

I update newest commit and rebuild package, however, image scaling issue is still there. Had tried to clear local storage. Anything I'm doing wrong?
<img width="1044" alt="Screen Shot 2021-11-17 at 10 44 59" src="https://user-images.githubusercontent.com/13161779/142116315-7a8e01e7-1dc7-4412-ae34-002ba68fff8e.png">

**Comment by ThomasFKJorna** [comment]
Aannnndd I did not yet implement this: stay tuned!

**Comment by ThomasFKJorna** [comment]
Should be supported now, although I can't really test it. (wait for the build to finish to check though)
